#Set port
server.port=8117

#Security settings
jwt.secret=qXj3W70YlVeVPfyzzdfCTwMiuYiVBqrv

#Database options
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver.class=oracle.jdbc.driver.OracleDriver