#Set port
server.port=8117

#Security settings
jwt.secret=qXj3W70YlVeVPfyzzdfCTwMiuYiVBqrv

#Database options
#Prod
spring.datasource.url=jdbc:mysql://localhost:3306/sambot_webapp
spring.datasource.username=sambobsambob
spring.datasource.password=SambotWebApp777!
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

#Dev
#spring.datasource.url=jdbc:mysql://localhost:3306/test_db
#spring.datasource.username=sambobsambob
#spring.datasource.password=test_db777
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver